In [11]:
import spacy
import pandas as pd

In [7]:
nlp=spacy.load('en_core_web_sm')
# en_core_web_sm is not dictonary but it is used to find the pattern in language
# if you are running this for the first time, or recieve an error "Can't find model 'en_core_web_sm'",
# then please run the follwing in your terminal: python -m spacy download en_core_web_sm

In [8]:
# our text is from jane austin's 'emma'
# we have removed punctuation, lowercased but left in stop words
emma_ja = "emma woodhouse handsome clever and rich with a comfortable home and happy disposition seemed to unite some of the best blessings of existence and had lived nearly twentyone years in the world with very little to distress or vex her she was the youngest of the two daughters of a most affectionate indulgent father and had in consequence of her sisters marriage been mistress of his house from a very early period her mother had died too long ago for her to have more than an indistinct remembrance of her caresses and her place had been supplied by an excellent woman as governess who had fallen little short of a mother in affection sixteen years had miss taylor been in mr woodhouses family less as a governess than a friend very fond of both daughters but particularly of emma between them it was more the intimacy of sisters even before miss taylor had ceased to hold the nominal office of governess the mildness of her temper had hardly allowed her to impose any restraint and the shadow of authority being now long passed away they had been living together as friend and friend very mutually attached and emma doing just what she liked highly esteeming miss taylors judgment but directed chiefly by her own"
print(emma_ja)

emma woodhouse handsome clever and rich with a comfortable home and happy disposition seemed to unite some of the best blessings of existence and had lived nearly twentyone years in the world with very little to distress or vex her she was the youngest of the two daughters of a most affectionate indulgent father and had in consequence of her sisters marriage been mistress of his house from a very early period her mother had died too long ago for her to have more than an indistinct remembrance of her caresses and her place had been supplied by an excellent woman as governess who had fallen little short of a mother in affection sixteen years had miss taylor been in mr woodhouses family less as a governess than a friend very fond of both daughters but particularly of emma between them it was more the intimacy of sisters even before miss taylor had ceased to hold the nominal office of governess the mildness of her temper had hardly allowed her to impose any restraint and the shadow of authority being now long passed away they had been living together as friend and friend very mutually attached and emma doing just what she liked highly esteeming miss taylors judgment but directed chiefly by her own

In [9]:
# create a spacy doc from our text - this will generate tokens and their assosciated pos tags
spacy_doc = nlp(emma_ja)

In [12]:
# extract the tokens and pos tags into a dataframe
pos_df = pd.DataFrame(columns=['token', 'pos_tag'])

In [16]:
for token in spacy_doc:
    pos_df = pd.concat([pos_df, pd.DataFrame.from_records([{'token':token.text, 'pos_tag':token.pos_}])],ignore_index=True)

# or
pos_data = [{'token':token.text, 'pos_tag':token.pos_} for token in spacy_doc]
pos_df = pd.DataFrame(pos_data)

In [17]:
pos_df

         token pos_tag
0         emma   PROPN
1    woodhouse   PROPN
2     handsome     ADJ
3       clever     ADJ
4          and   CCONJ
..         ...     ...
209   directed    VERB
210    chiefly     ADV
211         by     ADP
212        her    PRON
213        own     ADJ

[214 rows x 2 columns]

In [20]:
pos_df_counts = pos_df.groupby(['token', 'pos_tag']).size().reset_index(name='counts').sort_values(by='counts', ascending=False,ignore_index=True)
pos_df_counts

          token pos_tag  counts
0            of     ADP      14
1           her    PRON       9
2           had     AUX       9
3           and   CCONJ       8
4           the     DET       8
..          ...     ...     ...
127         who    PRON       1
128   woodhouse   PROPN       1
129  woodhouses   PROPN       1
130       world    NOUN       1
131    youngest     ADJ       1

[132 rows x 3 columns]

In [27]:
pos_df_count = pos_df_counts.groupby([ 'pos_tag']).size().reset_index(name='counts').sort_values(by='counts',ascending=False)
pos_df_count

   pos_tag  counts
6     NOUN      35
12    VERB      19
0      ADJ      18
2      ADV      18
9     PRON       9
1      ADP       8
10   PROPN       6
5      DET       5
3      AUX       4
4    CCONJ       3
7      NUM       3
11   SCONJ       3
8     PART       1

In [28]:
nouns  = pos_df_counts[pos_df_counts['pos_tag']=='NOUN'][0:10]

        token pos_tag  counts
10  governess    NOUN       3
11     friend    NOUN       3
13      years    NOUN       2
16  daughters    NOUN       2
17       emma    NOUN       2
21     mother    NOUN       2
27    sisters    NOUN       2
30  affection    NOUN       1
33  authority    NOUN       1
38   distress    NOUN       1